schema_version: 1

context:
  name: swan
  version: 41.51

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://swanmodel.sourceforge.io/download/zip/swan4151.tar.gz
  sha256: 5e30107af500cadf9d6d1b6076403cc85793fd4db113d6a487fede5f74f41f77

build:
  number: 2
  skip: win

requirements:
  build:
    - make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
  host:
    - perl
    - openmpi
    - netcdf-fortran
  run:
    - openmpi

tests:
  - script:
      - test -x ${PREFIX}/bin/swan.exe
      - test -x ${PREFIX}/bin/swanrun

about:
  license: GPL-3.0-or-later
  license_file: swanmain.f
  summary: A third-generation wave model, that computes random, short-crested wind-generated waves in coastal regions and inland waters.
  homepage: https://swanmodel.sourceforge.io/
  repository: https://swanmodel.sourceforge.io/online_doc/swanuse/swanuse.html
  documentation: https://swanmodel.sourceforge.io/

extra:
  recipe-maintainers:
    - martin-g
